# instance name
# no longer need declare shm_name and zmq_addr
# convention over configuration
# shm_name: cvmmap_{name}
# zmq_addr: ipc:///tmp/{shm_name}
name = 'example'
[video]
# opencv | gstreamer
backend = 'gstreamer'
use_finite_as_infinite_stream = false
finite_stream_ending_behavior = 'loop' # stop | loop
[opencv]
parameter = "example.mkv"
[gstreamer]
pipeline = "filesrc location=example.mkv ! decodebin ! videoconvert ! appsink name=sink"

[preprocess.undistort]
enabled = false
model = "pinhole"
camera_matrix = [1000.0, 0.0, 640.0, 0.0, 1000.0, 360.0, 0.0, 0.0, 1.0]
dist_coeffs = [0.0, 0.0, 0.0, 0.0, 0.0]
use_optimal_new_camera_matrix = true
alpha = 0.0
crop_to_valid_roi = false
strict_startup = false
