#include "app_backends_playlist.hpp"

#include <algorithm>
#include <memory>
#include <mutex>
#include <sstream>
#include <string_view>

#include <spdlog/spdlog.h>

#include "app_backends_mcap.hpp"
#include "app_backends_zed.hpp"
#include "app_config.hpp"

namespace {

std::string toml_quote_string(const std::string_view value) {
	std::string quoted{};
	quoted.reserve(value.size() + 2);
	quoted.push_back('"');
	for (const char ch : value) {
		if (ch == '\\' || ch == '"') {
			quoted.push_back('\\');
		}
		quoted.push_back(ch);
	}
	quoted.push_back('"');
	return quoted;
}

std::string format_zed_playlist_runtime_sort_snippet(const std::vector<std::string> &paths) {
	std::ostringstream ss{};
	ss << "# Runtime-resolved ZED playlist order generated by cv-mmap.\n";
	ss << "# Paste this into your config to avoid reopening each SVO during startup sorting.\n";
	ss << "[zed.playlist]\n";
	ss << "paths = [\n";
	for (const auto &path : paths) {
		ss << "  " << toml_quote_string(path) << ",\n";
	}
	ss << "]\n";
	ss << "sort_by_recording_time = false\n";
	return ss.str();
}

class RuntimePlaylistController final {
public:
	explicit RuntimePlaylistController(app::Config &config) : config_(config) {}

	[[nodiscard]]
	std::optional<cvmmap::PlaylistRequest> GetConfiguredRequest() const {
		switch (config_.video.backend) {
		case app::BackendType::MCAP:
			if (config_.mcap && config_.mcap->playlist) {
				return cvmmap::PlaylistRequest{
					.paths = config_.mcap->playlist->paths,
					.sort_by_recording_time = config_.mcap->playlist->sort_by_recording_time,
				};
			}
			return std::nullopt;
		case app::BackendType::ZED:
			if (config_.zed && config_.zed->stream_mode == "svo" && config_.zed->playlist) {
				return cvmmap::PlaylistRequest{
					.paths = config_.zed->playlist->paths,
					.sort_by_recording_time = config_.zed->playlist->sort_by_recording_time,
				};
			}
			return std::nullopt;
		default:
			return std::nullopt;
		}
	}

	[[nodiscard]]
	bool SupportsRuntimeApply() const {
		switch (config_.video.backend) {
		case app::BackendType::MCAP:
			return config_.mcap.has_value();
		case app::BackendType::ZED:
			return config_.zed.has_value() && config_.zed->stream_mode == "svo";
		default:
			return false;
		}
	}

	[[nodiscard]]
	bool HasPlaylist() const {
		std::lock_guard lock(state_mutex_);
		return state_.has_value();
	}

	[[nodiscard]]
	size_t Size() const {
		std::lock_guard lock(state_mutex_);
		return state_ ? state_->paths.size() : 0;
	}

	[[nodiscard]]
	size_t CurrentIndex() const {
		std::lock_guard lock(state_mutex_);
		return state_ ? state_->current_index : 0;
	}

	bool SetCurrentIndex(const size_t index) {
		std::lock_guard lock(state_mutex_);
		if (!state_ || index >= state_->paths.size()) {
			return false;
		}
		state_->current_index = index;
		return true;
	}

	[[nodiscard]]
	std::optional<std::string> CurrentPath() const {
		std::lock_guard lock(state_mutex_);
		if (!state_ || state_->paths.empty() || state_->current_index >= state_->paths.size()) {
			return std::nullopt;
		}
		return state_->paths[state_->current_index];
	}

	void ApplyCurrentPathToConfig() {
		auto current_path = CurrentPath();
		if (!current_path) {
			return;
		}
		switch (config_.video.backend) {
		case app::BackendType::MCAP:
			if (config_.mcap) {
				config_.mcap->path = *current_path;
			}
			break;
		case app::BackendType::ZED:
			if (config_.zed) {
				config_.zed->svo_path = *current_path;
			}
			break;
		default:
			break;
		}
	}

	[[nodiscard]]
	cvmmap::PlaylistInfo GetInfo() const {
		std::lock_guard lock(state_mutex_);
		cvmmap::PlaylistInfo info{};
		if (!state_) {
			return info;
		}
		info.has_playlist = true;
		info.paths = state_->paths;
		info.sort_by_recording_time = state_->sort_by_recording_time;
		info.current_index = static_cast<uint32_t>(state_->current_index);
		if (state_->current_index < state_->paths.size()) {
			info.current_path = state_->paths[state_->current_index];
		}
		return info;
	}

	[[nodiscard]]
	std::optional<app::backends::ResolvedPlaylistState> SnapshotState() const {
		std::lock_guard lock(state_mutex_);
		return state_;
	}

	void RestoreState(std::optional<app::backends::ResolvedPlaylistState> state) {
		std::lock_guard lock(state_mutex_);
		state_ = std::move(state);
	}

	void ReplaceState(app::backends::ResolvedPlaylistState state) {
		std::lock_guard lock(state_mutex_);
		state_ = std::move(state);
	}

	[[nodiscard]]
	cvmmap::expected<app::backends::ResolvedPlaylistState, cvmmap::ControlError>
	Resolve(const cvmmap::PlaylistRequest &request) const {
		if (request.paths.empty()) {
			return cvmmap::unexpected(cvmmap::ControlError{
				.code = cvmmap::ControlErrorCode::InvalidPayload,
				.message = "playlist paths must not be empty",
			});
		}
		for (const auto &path : request.paths) {
			if (path.empty()) {
				return cvmmap::unexpected(cvmmap::ControlError{
					.code = cvmmap::ControlErrorCode::InvalidPayload,
					.message = "playlist paths must not be empty",
				});
			}
		}

		app::backends::ResolvedPlaylistState resolved{
			.paths = request.paths,
			.sort_by_recording_time = request.sort_by_recording_time,
			.current_index = 0,
		};

		switch (config_.video.backend) {
		case app::BackendType::MCAP:
			if (!config_.mcap) {
				return cvmmap::unexpected(cvmmap::ControlError{
					.code = cvmmap::ControlErrorCode::Unsupported,
					.message = "MCAP playlist apply is unavailable without an active MCAP producer",
				});
			}
#ifdef WITH_BACKEND_MCAP
			if (resolved.sort_by_recording_time) {
				struct ProbeResult {
					std::string path;
					uint64_t start_timestamp_ns{0};
				};
				std::vector<ProbeResult> probes{};
				probes.reserve(resolved.paths.size());
				for (const auto &path : resolved.paths) {
					auto probe_config = *config_.mcap;
					probe_config.path = path;
					auto probe = app::backends::ProbeMcapStartTimestampNs(probe_config);
					if (!probe) {
						return cvmmap::unexpected(cvmmap::ControlError{
							.code = cvmmap::ControlErrorCode::Error,
							.message = cvmmap::format(
								"MCAP playlist probe failed for '{}': {}",
								path,
								probe.error()),
						});
					}
					probes.push_back(ProbeResult{
						.path = path,
						.start_timestamp_ns = *probe,
					});
				}
				std::stable_sort(probes.begin(), probes.end(), [](const auto &lhs, const auto &rhs) {
					return lhs.start_timestamp_ns < rhs.start_timestamp_ns;
				});
				resolved.paths.clear();
				for (const auto &probe : probes) {
					resolved.paths.push_back(probe.path);
				}
			}
			return resolved;
#else
			return cvmmap::unexpected(cvmmap::ControlError{
				.code = cvmmap::ControlErrorCode::Unsupported,
				.message = "MCAP playlist apply is unavailable in this build",
			});
#endif
		case app::BackendType::ZED:
			if (!config_.zed || config_.zed->stream_mode != "svo") {
				return cvmmap::unexpected(cvmmap::ControlError{
					.code = cvmmap::ControlErrorCode::Unsupported,
					.message = "ZED playlist apply is only supported for stream_mode='svo'",
				});
			}
#ifdef WITH_BACKEND_ZED
			if (resolved.sort_by_recording_time) {
				spdlog::warn(
					"zed.playlist.sort_by_recording_time is discouraged: cv-mmap opens each SVO serially to probe its first frame timestamp, "
					"which can make startup or playlist apply slow. Prefer pre-sorting with zed-offline-tools/scripts/generate_playlist_config.py --sort-by-recording-time.");
				struct ProbeResult {
					std::string path;
					uint64_t start_timestamp_ns{0};
				};
				std::vector<ProbeResult> probes{};
				probes.reserve(resolved.paths.size());
				for (const auto &path : resolved.paths) {
					auto probe_config = *config_.zed;
					probe_config.svo_path = path;
					auto probe = app::backends::ProbeZedSvoStartTimestampNs(probe_config);
					if (!probe) {
						return cvmmap::unexpected(cvmmap::ControlError{
							.code = cvmmap::ControlErrorCode::Error,
							.message = cvmmap::format(
								"ZED playlist probe failed for '{}': {}",
								path,
								probe.error()),
						});
					}
					probes.push_back(ProbeResult{
						.path = path,
						.start_timestamp_ns = *probe,
					});
				}
				std::stable_sort(probes.begin(), probes.end(), [](const auto &lhs, const auto &rhs) {
					return lhs.start_timestamp_ns < rhs.start_timestamp_ns;
				});
				resolved.paths.clear();
				for (const auto &probe : probes) {
					resolved.paths.push_back(probe.path);
				}
				spdlog::warn(
					"runtime-sorted ZED playlist result; paste this into config and keep runtime sorting disabled:\n{}",
					format_zed_playlist_runtime_sort_snippet(resolved.paths));
			}
			return resolved;
#else
			return cvmmap::unexpected(cvmmap::ControlError{
				.code = cvmmap::ControlErrorCode::Unsupported,
				.message = "ZED playlist apply is unavailable in this build",
			});
#endif
		default:
			return cvmmap::unexpected(cvmmap::ControlError{
				.code = cvmmap::ControlErrorCode::Unsupported,
				.message = "playlist apply is only supported for MCAP and ZED SVO producers",
			});
		}
	}

private:
	app::Config &config_;
	mutable std::mutex state_mutex_{};
	std::optional<app::backends::ResolvedPlaylistState> state_{};
};

} // namespace

namespace app::backends {

pro::proxy<IPlaylistController> MakePlaylistController(app::Config &config) {
	return std::make_unique<RuntimePlaylistController>(config);
}

} // namespace app::backends
